name: Andrey Terentyev Photographer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56411
title: Andrey Terentyev Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#272526'
    - '#606062'
    - '#9a9b9f'
    - '#b07a68'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4699962972663343
  rhythmicContrast: 0.5
purpose: []
